### ISSUE TITLE
ESP8266 compatibility?

### ISSUE THREAD

**Issue by tolgaberk** [arduino-libraries/Arduino_OV767X#15]
Hi, thanks for the hard work guys.

I am kinda new to this kind of stuff and i was wondering if this library is compatible with esp8266 chip with arduino framework?

Can i make it work just by changing pins in header files?

Thanks a lot.

**Comment by per1234** [comment]
Hi @tolgaberk. Thanks for your interest in the Arduino_OV767X library. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to answer your question over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
