### ISSUE TITLE
Is this library compatible with Arduino Nano RP2040 Connect?

### ISSUE THREAD

**Issue by zyh19990515** [arduino-libraries/Arduino_OV767X#23]
Is this library compatible with Arduino Nano RP2040 Connect?
When i use the example code,there are lots of "not declared" such as "NRF_P0","rf_gpio_pin_port_decode".

**Comment by per1234** [comment]
Hi @zyh19990515. There is an answer to your question here: https://github.com/arduino-libraries/Arduino_OV767X/issues/9#issuecomment-762729202

> this library was specifically designed for the Arduino Nano 33 BLE / BLE Sense
