### ISSUE TITLE
BLE and OV7670 don't work together

### ISSUE THREAD

**Issue by onderbedirhan** [arduino-libraries/Arduino_OV767X#27]
I designed a custom board with nRF 52840 microcontroller. And I use adafruit arduino core(Feather 52840 express) and bootloaders.
When I use 0V760 camera and BLE with together BLE crashed.Because 0V7670 library call noInterrupts() function and this function
cause BLE crashed. As a solution to this problem I use sd_nvic_critical_region_enter/exit functions but when ı 
use these functions lines appear in the camera image. Is there any way to fix this problem?

**Comment by per1234** [comment]
Hi @onderbedirhan. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
