### ISSUE TITLE
COM5: Serial port naming on Windows

### ISSUE THREAD

**Issue by 8bitkick** [arduino-libraries/Arduino_OV767X#3]
From[ blog](https://blog.arduino.cc/2020/06/24/machine-vision-with-low-cost-camera-modules/) comment: 

> The CameraVisualizerRawBytes for Processing didn’t work on Windows, until I changed the serial port from “COM5:” to “COM5”. I think the : symbol is a typo maybe?

A quick fix but I don't have a windows machine to test this on

**Comment by facchinm** [comment]
Yep, it's a typo, fixing now :slightly_smiling_face: Thanks for reporting!
